server:
  port: 8080
  
spring:
  application:
    name: orangecar
  datasource:
    url: jdbc:mysql://10.102.1.121:3306/carrent?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小、最小、最大连接数
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 监控后台账号和密码
      stat-view-servlet:
        enabled: true
        reset-enable: true
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
      # 配置 StatFilter
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  thymeleaf:
    cache: false
    encoding: UTF-8


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qsd.orange.po

