server:
  port: 8080
  
spring:
  application:
    name: orangecar
  datasource:
    url: jdbc:mysql://10.102.1.121:3306/carrent?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qsd.orange.po

